name: apr
description: Neoflex apr template

publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  apr_sdk:
    git:
      url: git@gitlab.kantar-tns.local:mediascope/ui/apr-sdk.git
      ref: 0.0.37
    # path: ../apr-sdk
  collection: ^1.17.1
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.3.4
  event_bus: ^2.0.0
  feature_flags_toggly: ^1.0.5
  firebase_analytics: ^10.10.7
  firebase_core: ^2.32.0
  firebase_remote_config: ^4.4.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.4+2
  flutter_secure_storage: ^9.0.0
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.9
  flutter_watermark: ^1.0.2
  flutter_widget_from_html: ^0.15.2
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  go_router: ^13.2.0
  google_fonts: ^6.1.0
  graphql_flutter: ^5.1.2
  highlight_text: ^1.7.0
  hydrated_bloc: ^9.1.5
  intl: ^0.19.0
  intl_generator: ^0.4.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  jwt_decoder: ^2.0.1
  local_auth: ^2.1.7
  opo_ui_kit_r:
    git:
      url: git@gitlab.kantar-tns.local:mediascope/ui/apr-ui-kit.git
      ref: 0.0.157
    # path: ../apr-ui-kit
  otp_text_field: ^1.1.3
  retrofit: ^4.0.3
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  super_banners: ^0.0.1
  talker: 4.1.0
  talker_dio_logger: ^4.1.0
  talker_flutter: ^4.1.0
  timeago: ^3.7.0
  toastification: ^2.3.0
  url_launcher: ^6.2.5

dev_dependencies:
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  graphql_codegen: ^0.14.0
  process_run: ^0.14.2
  retrofit_generator: ^8.0.4
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/l10n/
    - assets/launcher_icon/
    - assets/json_for_tests/
    - assets/icons/
    - .prod.env
    - .dev.env
